import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from 'src/app/service/backendgameapi/api.service';
// import { Location } from '@angular/common';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { NgApexchartsModule } from 'ng-apexcharts';

@Component({
  selector: 'app-crmcaseheader',
  standalone: true,
  imports: [CommonModule, FormsModule,MatIconModule,NgApexchartsModule],
  templateUrl: './crmcaseheader.component.html',
  styleUrls: ['./crmcaseheader.component.scss']
})
export class CrmcaseheaderComponent implements OnInit {

  constructor(private _router: Router,
    private _api: ApiService
  ) { }

  ngOnInit(): void {
  }

  activeTab = 'market';
  search(activeTab: any) {
    this.activeTab = activeTab;
  }

  GoBack() {
    this._api.GoBack();
  }

  languagebody: any = [
    {
      heading: "Introduction",
      body: [

        { english: "How it is work", others: "b7" },
        { english: "Understand your role within the industry, evaluate prevailing macroeconomic conditions, and pinpoint market opportunities to strategically position your efforts for maximum impact.", others: "b8" },
        { english: "Delve into historical trends, dissect patterns, and identify overlooked opportunities through meticulous analysis, providing a solid foundation for informed decision-making.", others: "b9" },
        { english: "Streamline existing leads through thorough analysis, defining clear pathways for nurturing and conversion, ensuring an optimized sales pipeline for sustained growth.", others: "b10" },
        { english: "Tailor communication channels, and timing of follow-ups, and capitalize on cross-selling and upselling prospects, while curating campaigns to precisely nurture leads and drive engagement while maximizing returns on investment.", others: "b11" },
        { english: "Strategically allocate resources based on meticulously forecasted needs, while optimizing customer service strategies and streamlining process to enhance overall customer satisfaction.", others: "b12" },
        { english: "Gain comprehensive insights into revenue streams, customer satisfaction levels, incurred costs, lead response times, and pipeline velocity, leveraging this data for strategic decision-making and continual process enhancement.", others: "b13" },
        { english: "Market", others: "b14" },
        { english: "Information", others: "b15" },
        { english: "Lead Management", others: "b16" },
        { english: "Communication", others: "b17" },
        { english: "Process", others: "b18" },
        { english: "Reports", others: "b19" },
      ]
    },
    {
      heading: "Headings",
      body: [
        { english: "Decision Cheklist", others: "b20" },
        { english: "Synopsis", others: "b21" },
        { english: "Food For Thought", others: "b22" },
      ]

    },
    {
      heading: "Market",
      body: [
        { english: "In the bustling city of Bengaluru, a pioneering tech company has emerged, revolutionizing industries with its innovative blockchain solutions. Founded on the principles of transparency, efficiency, and security, this company has developed software that seamlessly manages records, streamlines processes, and provides a unified, tamper-proof infrastructure for businesses across various sectors. With a focus on enhancing supply chain management, the company has swiftly become a trusted partner for organizations seeking cutting-edge solutions to navigate the complexities of modern business operations.\n\nDespite its remarkable success, the company faces a significant challenge in maintaining strong relationships with its clients. While experiencing a commendable growth rate of 20% year-on-year, the team has recognized a pressing need to improve customer retention, streamline follow-ups, and prioritize opportunities effectively. With a clientele primarily comprising healthcare, technology, and retail industries in the Indian market, the company is keenly aware of the importance of nurturing these relationships to sustain its growth trajectory and continue delivering value to its customers.\n\nRecognizing the critical role that CRM expertise plays in addressing these challenges, the company seeks outside assistance to optimize its client management processes. As a seasoned CRM expert, you are invited to join forces with the company, leveraging your skills and insights to implement effective strategies for customer retention, follow-up management, and opportunity prioritization. Together, you embark on a journey to propel the company to new heights, ensuring that its pioneering blockchain solutions continue to empower businesses and drive success in the dynamic Indian market.", others: "b23" },
      ]
    },
    {
      heading: "Information",
      body: [
        { english: "Lead & Pipeline Management", others: "b24" },
        { english: "Lead Status Terminology", others: "b25" },
        { english: "New Lead", others: "b26" },
        { english: "Contacted", others: "b27" },
        { english: "Follow-up Scheduled", others: "b28" },
        { english: "Proposal Sent", others: "b29" },
        { english: "Closed-Won", others: "b30" },
        { english: "Closed-Lost", others: "b31" },
        { english: "Stages in Sales Cycle", others: "b32" },
        { english: "Awareness", others: "b33" },
        { english: "Interest", others: "b34" },
        { english: "Action", others: "b35" },
        { english: "Decision", others: "b36" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the lead conversion rate.", others: "b37" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the days.", others: "b38" },
        { english: "Communication Strategy", others: "b39" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the hours.", others: "b40" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the satisfaction score.", others: "b41" },
        { english: "Customer Service", others: "b42" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the response rate.", others: "b43" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the days.", others: "b44" },
        { english: "Cross-Selling & Upselling", others: "b45" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the rate.", others: "b46" },
        { english: "Resources & Value", others: "b47" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the cost.", others: "b48" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the order value.", others: "b49" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the frequency.", others: "b50" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the years.", others: "b51" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the rate.", others: "b52" },
        { english: "Revenue Streams", others: "b53" },
        { english: "The x-axis represents the data of the last 3 years where P3 represents the previous year, while the y-axis represents the revenue.", others: "b54" },
        { english: "New leads have been identified, but they are still in the early stages of the sales cycle. The company may need to conduct further qualification and discovery activities to determine their potential as customers.", others: "b55" },
        { english: "At this stage, leads have shown initial interest in the company's offerings. They may have filled out an online form, made an inquiry via email, or visited the company's booth at a trade show.", others: "b56" },
        { english: "Leads in this stage have been contacted by the company, and follow-up activities such as phone calls, emails, or meetings have been scheduled to further explore their requirements and move them through the sales process.", others: "b57" },
        { english: "The company has submitted a formal proposal or quotation to the leads outlining the proposed solution, pricing, and terms. The leads are reviewing the proposal and evaluating whether it meets their needs.", others: "b58" },
        { english: "This stage indicates that the company has successfully closed the deal and won the business from the leads. Contracts may have been signed, and the implementation process may be underway.", others: "b59" },
        { english: "Leads in this stage have decided not to move forward with the company's proposal. The deal has been lost, and the company may have identified reasons for the loss to inform future sales efforts.", others: "b60" },
        { english: "This stage represents the beginning of the sales journey, where leads become aware of the company and its offerings but have not yet progressed to active engagement or consideration.", others: "b61" },
        { english: "This stage represents the beginning of the sales cycle, where leads express interest in learning more about the product or service.", others: "b62" },
        { english: "This stage indicates a higher level of engagement and involvement in the sales process.", others: "b63" },
        { english: "This stage may involve evaluating the benefits, features, and pricing of the offering, as well as addressing any concerns or objections raised by the leads.", others: "b64" },
      ],
    },
    {
      heading: "Information Graph",
      body: [
        { english: "Lead Conversion Rate", others: "b65" },
        { english: "Pipeline Velocity, days", others: "b66" },
        { english: "Average Lead Response Time, hours", others: "b67" },
        { english: "Customer Satisfaction Score", others: "b68" },
        { english: "Customer Service Response Rate", others: "b69" },
        { english: "Average Resolution Time, days", others: "b70" },
        { english: "Rate %", others: "b71" },
        { english: "Customer Acquisition Cost, INR", others: "b72" },
        { english: "Average Purchase Order, INR", others: "b73" },
        { english: "Average frequency per year", others: "b74" },
        { english: "Life Span, years", others: "b75" },
        { english: "Churn Rate %", others: "b76" },
        { english: "Total Revenue, INR", others: "b77" },
        { english: "Revenue Distribution by Industry, P3", others: "b78" },
      ],
    },
    {
      heading: "Lead",
      body: [
        { english: "Lead", others: "b79" },
        { english: "High", others: "b80" },
        { english: "Medium", others: "b81" },
        { english: "Low", others: "b82" },
        { english: "Indicates a pressing requirement for attention and follow-up to capitalize on potential opportunities.", others: "b83" },
        { english: "Requiring attention and follow-up but not as immediate as high-priority leads.", others: "b84" },
        { english: "Indicating that follow-up and engagement can be deferred or approached more casually.", others: "b85" },
        { english: "Lead ID", others: "b86" },
        { english: "Contact Information", others: "b87" },
        { english: "Lead Source", others: "b88" },
        { english: "Industry", others: "b89" },
        { english: "Budget", others: "b90" },
        { english: "Urgency", others: "b91" },
        { english: "Lead Score", others: "b92" },
        { english: "Industry", others: "b93" },
        { english: "Budget", others: "b94" },
        { english: "Lead Status", others: "b95" },
        { english: "Stage in Sales Cycle", others: "b96" },
        { english: "Next Steps", others: "b97" },
        { english: "Follow-up Actions", others: "b98" },
        { english: "Priority", others: "b99" },
        { english: "Rahul Gupta", others: "b100" },
        { english: "Priya Sharma", others: "b101" },
        { english: "Ravi Singh", others: "b102" },
        { english: "Neha Patel", others: "b103" },
        { english: "Shikha Jain", others: "b104" },
        { english: "Rohan Verma", others: "b105" },
        { english: "Aarav Khanna", others: "b106" },
        { english: "Ananya Dubey", others: "b107" },
        { english: "Sameer Sharma", others: "b108" },
        { english: "Priyanka Patel", others: "b109" },
        { english: "Arjun Singh", others: "b110" },
        { english: "Akash Gupta", others: "b111" },
        { english: "Ayesha Khan", others: "b112" },
        { english: "Saurabh Verma", others: "b113" },
        { english: "Natasha Singh", others: "b114" },
        { english: "Sumit Sharma", others: "b115" },
        { english: "Anjali Patel", others: "b116" },
        { english: "Vikram Singh", others: "b117" },
        { english: "Deepak Sharma", others: "b118" },
        { english: "Priya Verma", others: "b119" },
        { english: "Ramesh Patel", others: "b120" },
        { english: "Nisha Gupta", others: "b121" },
        { english: "Vivek Singh", others: "b122" },
        { english: "Tanvi Patel", others: "b123" },
        { english: "Rajesh Sharma", others: "b124" },
        { english: "Online Form", others: "b125" },
        { english: "Email Inquiry", others: "b126" },
        { english: "Trade Show Visit", others: "b127" },
        { english: "Referral", others: "b128" },
        { english: "Healthcare", others: "b129" },
        { english: "Technology", others: "b130" },
        { english: "Retail", others: "b131" },
        { english: "Immediate Need", others: "b132" },
        { english: "Urgent", others: "b133" },
        { english: "Future Potential", others: "b134" },
        { english: "Schedule Demo", others: "b135" },
        { english: "Proposal Preparation", others: "b136" },
        { english: "Follow-up Call", others: "b137" },
        { english: "Negotiation", others: "b138" },
        { english: "Implementation", others: "b139" },
        { english: "Email Follow-up", others: "b140" },
        { english: "Phone Call", others: "b141" },
        { english: "In-person Meeting", others: "b142" },
        { english: "Cross Selling & Upselling", others: "b372" },
        { english: "Impact", others: "b373" },
        { english: "Cost per year", others: "b374" },
        { english: "Effect", others: "b375" },
        { english: "Probability of conversion", others: "b376" },
        { english: "Extra hours, yearly", others: "b377" },
        { english: "follow-up frequency, day", others: "b378" },
        { english: "follow-up timeline, week", others: "b379" },
        { english: "allocated hours, customer enhancement", others: "b380" },
        { english: "allocated hours, lead management", others: "b381" },
        { english: "Contacted", others: "b382" },
        { english: "Follow-up Scheduled", others: "b383" },
        { english: "New Lead", others: "b384" },
        { english: "Proposal Sent", others: "b385" },
        { english: "Closed-Won", others: "b386" },
        { english: "Closed-Lost", others: "b387" },
        { english: "Process Streamlining", others: "b388" },
        { english: "Leads who have shown interest in specific products or services", others: "b389" },
        { english: "Educate and engage leads by offering valuable insights and knowledge", others: "b390" },
        { english: "Provide personalized product demonstrations to address lead-specific needs and objections", others: "b391" },
        { english: "Cross-Selling Rate", others: "b392" },
        { english: "Up-Selling Rate", others: "b393" },
      
      ],
    },
    {
      heading: "Communication",
      body: [
        { english: "Communication Strategy", others: "b143" },
        { english: "High Priority Leads", others: "b144" },
        { english: "Medium Priority Leads", others: "b145" },
        { english: "Low Priority Leads", others: "b146" },
        { english: "Phone Calls", others: "b147" },
        { english: "Personalized Email", others: "b148" },
        { english: "Targeted Content", others: "b149" },
        { english: "Informative Content", others: "b150" },
        { english: "Case Studies", others: "b151" },
        { english: "Success Stories", others: "b152" },
        { english: "Educational Content", others: "b153" },
        { english: "Newsletter", others: "b154" },
        { english: "Occasional Check-ins", others: "b155" },
        { english: "Follow-up Frequency, day", others: "b156" },
        { english: "Follow-up Timeline, week", others: "b157" },
        { english: "Cross-Selling & Upselling", others: "b158" },
        { english: "Lead Nurturing", others: "b159" },
        { english: "Audience Target", others: "b160" },
        { english: "Objective", others: "b161" },
        { english: "Message", others: "b162" },
        { english: "Channel", others: "b163" },
        { english: "Cost", others: "b164" },
        { english: "Past Engagement", others: "b165" },
        { english: "Social Media Engagement Challenge", others: "b166" },
        { english: "Personalized Email Newsletter", others: "b167" },
        { english: "Webinar Series Invitation", others: "b168" },
        { english: "Exclusive Product Demo", others: "b169" },
        { english: "Leads with active social media presence or engagement history", others: "b170" },
        { english: "Encourage leads to interact with the brand and share their experiences on social media", others: "b171" },
        { english: "Launch a social media challenge or contest encouraging leads to share their experiences, testimonials, or user-generated content related to the brand or products", others: "b172" },
        { english: "Social media platforms", others: "b173" },
        { english: "200 contest entries, 300 new followers", others: "b174" },
        { english: "Nurture leads and provide valuable content to maintain engagement", others: "b175" },
        { english: "Tailored content highlighting relevant industry news, product updates, and exclusive offers based on lead preferences", others: "b176" },
        { english: "Email marketing", others: "b177" },
        { english: "20% open rate, 5% conversion rate", others: "b178" },
        { english: "Leads in the consideration stage who may benefit from in-depth educational content", others: "b179" },
        { english: "Invite leads to participate in a series of educational webinars covering topics relevant to their interests or pain points", others: "b180" },
        { english: "Email marketing and social media", others: "b181" },
        { english: "300 registrations, 50% attendance rate", others: "b182" },
        { english: "Leads who have shown interest in specific products but have not yet made a purchase decision", others: "b183" },
        { english: "Offer an exclusive opportunity for leads to schedule a personalized product demo tailored to their requirements", others: "b184" },
        { english: "Direct outreach via phone calls or personalized emails", others: "b185" },
        { english: "10% response rate, 2% conversion rate", others: "b186" },
      ],
    },
    {
      heading: "Process",
      body: [
        { english: "Customer Service Enhancement", others: "b187" },
        { english: "Onboarding and Implementation Support", others: "b188" },
        { english: "Ongoing Technical Support", others: "b189" },
        { english: "Customer Relationship Management", others: "b190" },
        { english: "Feedback Collection and Product Improvement", others: "b191" },
        { english: "Issue Resolution and Escalation", others: "b192" },
        { english: "By offering extended onboarding sessions and personalized implementation assistance, customer satisfaction can increase by up to 5%, leading to improved understanding and utilization of the product.", others: "b193" },
        { english: "Strengthening technical support with faster response times and deeper troubleshooting capabilities can boost customer satisfaction by 3%, fostering trust and confidence in the company's products.", others: "b194" },
        { english: "Enhancing CRM efforts with more frequent check-ins, tailored communication, and proactive problem-solving can elevate customer satisfaction by 4%, fostering loyalty and increasing the likelihood of repeat purchases.", others: "b195" },
        { english: "Improving feedback collection processes and prioritizing product improvements based on customer input can boost satisfaction by 2%, demonstrating responsiveness to customer needs.", others: "b196" },
        { english: "Strengthening issue resolution capabilities with faster response times and proactive communication can elevate satisfaction by 3%, instilling confidence in the company's support infrastructure.", others: "b197" },
        { english: "Process Streamline", others: "b198" },
        { english: "Automated Data Entry and Integration", others: "b199" },
        { english: "Cloud-Based CRM Solution", others: "b200" },
        { english: "Self-Service Customer Portal", others: "b201" },
        { english: "AI-Powered Chatbots for Customer Support", others: "b202" },
        { english: "Process Standardization and Documentation", others: "b203" },
        { english: "By automating data entry and integrating CRM with other systems like accounting or project management, the company can streamline workflows, improve data accuracy, and reduce operational costs associated with manual data entry and reconciliation.", others: "b204" },
        { english: "Moving CRM to the cloud reduces upfront investment in hardware and software, lowers maintenance costs, and enables the company to adapt quickly to changing business needs without incurring additional infrastructure expenses.", others: "b205" },
        { english: "By empowering customers to find answers to common queries, update their information, or troubleshoot issues through a self-service portal, the company can decrease the volume of support tickets and associated costs, while improving overall customer experience.", others: "b206" },
        { english: "By leveraging AI chatbots to handle routine customer queries 24/7, the company can improve responsiveness, lower staffing costs, and enhance operational efficiency, while ensuring consistent and timely support for customers.", others: "b207" },
        { english: "By documenting standardized CRM processes, the company can minimize errors, increase productivity, and reduce training time for new employees, resulting in significant cost savings and improved overall performance.", others: "b208" },
        { english: "Resources Needed", others: "b209" },
        { english: "Customer enhancement required hours", others: "b210" },
        { english: "Lead management required hours", others: "b211" },
        { english: "Average resource cost per hour", others: "b212" },
        { english: "Allocated hours, Customer enhancement", others: "b213" },
        { english: "Allocated hours, Lead management", others: "b214" },
        { english: "Deficit/Surplus (-/+)", others: "b215" },
        { english: "Estimated hours, yearly", others: "b216" },
        { english: "Cost, yearly", others: "b217" },
      ],
    },
    {
      heading: "Process Graph",
      body: [
        { english: "Resources", others: "b218" },
        { english: "Total hours required", others: "b219" },
        { english: "Total hours allocated", others: "b220" },
      ],
    },
    {
      heading: "Decisiion Checklist",
      body: [
        { english: "High Priority, Follow-up Frequency, day", others: "b221" },
        { english: "High Priority, Follow-up Timeline, week", others: "b222" },
        { english: "Medium Priority, Follow-up Frequency, day", others: "b223" },
        { english: "Medium Priority, Follow-up Timeline, week", others: "b224" },
        { english: "Low Priority, Follow-up Frequency, day", others: "b225" },
        { english: "Low Priority, Follow-up Timeline, week", others: "b226" },
        { english: "Describe your thought process behind the decision-making in 100 words…", others: "b227" },
      ],
    },
    {
      heading: "Report",
      body: [
        { english: "High Priority", others: "b228" },
        { english: "Medium Priority", others: "b229" },
        { english: "Low Priority", others: "b230" },
        { english: "Allocated", others: "b231" },
        { english: "Required", others: "b232" },
        { english: "Surplus (+)/Deficit (-)", others: "b233" },
        { english: "Increment (+)/Reduction (-) compared to last period P3", others: "b234" },
        { english: "Cross selling & upselling opportunities", others: "b235" },
        { english: "Customer service response rate", others: "b236" },
        { english: "Average resolution time", others: "b237" },
        { english: "Pipeline Velocity, days", others: "b238" },
        { english: "Previous Period CLV", others: "b239" },
        { english: "Expected New CLV", others: "b240" },
        { english: "Increment (+)/Reduction (-) CLV", others: "b241" },
        { english: "Chances of achieving Increment (+)/Reduction (-)", others: "b242" },
        { english: "Expected New Value", others: "b243" },
        { english: "Resource Cost", others: "b244" },
        { english: "Streamlining Cost", others: "b245" },
        { english: "Total Cost", others: "b246" },
        { english: "Value Creation", others: "b247" },
        { english: "Lead Pipeline Count", others: "b248" },
        { english: "Sales Conversion Chances", others: "b249" },
        { english: "Resource Allocation, hours", others: "b250" },
        { english: "KPI Variation", others: "b251" },
        { english: "Value Creation, INR", others: "b252" },
        { english: "Sales", others: "b253" },
        { english: "Service", others: "b254" },
        { english: "Excellent work. You have completed enhancing and optimizing the CRM for your technology company. In this exercise, every decision you have taken shows your skills in dimensions like rigor, synthesis, structuring, and business judgment.", others: "b255" },
      ],
    },
    {
      heading: "Report Graph",
      body: [
        { english: "Pipeline Management", others: "b256" },
        { english: "Rigor", others: "b257" },
        { english: "Structuring", others: "b258" },
        { english: "Synthesis", others: "b259" },
        { english: "Business Judgement", others: "b260" },
        { english: "You", others: "b400" },
        { english: "90% Percentile", others: "b401" },
        { english: "Average", others: "b402" },
        { english: "Consistency throughout the decision-making and recommendation.", others: "b403" },
        { english: "A logical approach to gathering and analyzing information.", others: "b404" },
        { english: "Approach towards interpreting all the information and making informed decisions.", others: "b405" },
        { english: "Ability to evaluate facts and consider risks and possible implications when making decisions.", others: "b406" },
      ],
    },
    {
      heading: "Synopsis",
      body: [
        { english: "Parameters", others: "b261" },
        { english: "Input", others: "b262" },
        { english: "Output", others: "b263" },
        { english: "Score", others: "b264" },
        { english: "Thinking Ability", others: "b394" },
      ],
    },
    {
      heading: "Hints",
      body: [
        { english: "Q1 How has the company's performance trended over the past 3 years based on historical data?", others: "b265" },
        { english: "Q2 What insights can be drawn from these trends to inform decision-making?", others: "b266" },
        { english: "Q1 In which stage of the sales cycle are the majority of leads currently?", others: "b267" },
        { english: "Q2 What criteria did you consider in making priority assignments?", others: "b268" },
        { english: "Q1 Considering the urgency, potential value, and readiness to purchase of each lead, what strategies would you employ to maximize conversion rates across all priority levels?", others: "b269" },
        { english: "Q2 What communication frequency and follow-up timeline would you recommend to ensure timely engagement?", others: "b270" },
        { english: "Q1 When is the most opportune time to introduce cross-selling and upselling opportunities to leads in various stages of the sales cycle?", others: "b271" },
        { english: "Q1 Which campaigns will resonate with the different leads in communication strategies?", others: "b272" },
        { english: "Q1 How can the company enhance the customer experience?", others: "b273" },
        { english: "Q2 Considering the decisions made regarding customer enhancement, how do these align with the overall strategic goals of the company?", others: "b274" },
        { english: "Q1 How many surplus hours need to be allocated to manage customer experience?", others: "b275" },
        { english: "Q2 What measures will you take to optimize the cost of resources by using sales and service as a tool?", others: "b276" },
        { english: "Q1 What measures would you implement to streamline processes and improve operational efficiency?", others: "b277" },
        { english: "Q2 What potential impact do they have on long-term growth and success?", others: "b278" },

      ],
    },
    {
      heading: "FoT",
      body: [
        { english: "Food For Thought", others: "b279" },
        { english: "Q1 How can historical data inform decision-making?", others: "b280" },
        { english: "Q2 What criteria should be considered in prioritizing leads?", others: "b281" },
        { english: "Q3 How can communication frequency be optimized for timely engagement?", others: "b282" },
        { english: "Q4 When is the best time to introduce cross-selling and upselling opportunities?", others: "b283" },
        { english: "Q5 Which type of campaigns resonate best with leads in communication strategies?", others: "b284" },
        { english: "Q6 How can customer experience be enhanced?", others: "b285" },
        { english: "Q7 How can surplus hours be allocated to manage customer experience?", others: "b286" },
        { english: "Q8 What measures optimize the cost of resources in sales and service?", others: "b287" },
        { english: "Q9 How can processes be streamlined to improve operational efficiency?", others: "b288" },
        { english: "1 By analyzing the parameters which are low as per company objective", others: "b289" },
        { english: "2 By analyzing trends and patterns", others: "b290" },
        { english: "3 By following gut feelings with some patterns", others: "b291" },
        { english: "1 On basis of the lead score only", others: "b292" },
        { english: "2 Urgency, potential value, and readiness to purchase", others: "b293" },
        { english: "3 Lead status and stage in sales cycle", others: "b294" },
        { english: "1 Communicate with every lead at the same pace", others: "b295" },
        { english: "2 Tailor communication based on lead priority and behavior", others: "b296" },
        { english: "3 Send mass emails daily", others: "b297" },
        { english: "1 After the sale", others: "b298" },
        { english: "2 Throughout the customer journey", others: "b299" },
        { english: "3 During the initial contact", others: "b300" },
        { english: "1 Mass campaigns talking about general problems and solutions", others: "b301" },
        { english: "2 Targeted campaigns aligned with lead preferences", others: "b302" },
        { english: "3 Campaigns with attractive content", others: "b303" },
        { english: "1 Customer service has to be only improved till certain point", others: "b304" },
        { english: "2 Continuously improve service based on tracking data", others: "b305" },
        { english: "3 Provide consistent service", others: "b306" },
        { english: "1 None", others: "b307" },
        { english: "2 Limited hours", others: "b308" },
        { english: "3 Adequate hours for optimal service delivery", others: "b309" },
        { english: "1 Increase resource spending", others: "b310" },
        { english: "2 Optimize resource allocation for cost efficiency", others: "b311" },
        { english: "3 Decrease resource spending", others: "b312" },
        { english: "1 Maintain the status quo", others: "b313" },
        { english: "2 Identify the process which increases pipeline velocity", others: "b314" },
        { english: "3 Implement the process which makes process cost effective in long-term", others: "b315" },
        { english: "Ignoring some of the historical data can lead to missed insights and opportunities for informed decision-making.", others: "b316" },
        { english: "Correct! Analyzing historical trends and patterns allows for informed decision-making.", others: "b317" },
        { english: "Relying on intuition or gut feelings without considering all historical data may lead to suboptimal decision-making.", others: "b318" },
        { english: "Relying only on lead score for prioritization overlooks critical factors such as urgency, potential value, and readiness to purchase.", others: "b319" },
        { english: "Correct! Prioritizing leads based on urgency, potential value, and readiness to purchase helps focus efforts on high-value leads.", others: "b320" },
        { english: "Prioritizing leads based on status and stage cycle does not consider factors such as urgency or potential value.", others: "b321" },
        { english: "Communicating with leads at the same pace may result in missed opportunities and decreased engagement.", others: "b322" },
        { english: "Correct! Tailoring communication frequency based on lead priority and behavior ensures timely engagement.", others: "b323" },
        { english: "Sending mass emails daily may lead to email fatigue and decreased engagement among leads.", others: "b324" },
        { english: "Introducing cross-selling and upselling opportunities after the sale may miss additional revenue opportunities.", others: "b325" },
        { english: "Correct! Introducing cross-selling and upselling throughout the customer journey maximizes exposure to relevant offers.", others: "b326" },
        { english: "Limiting cross-selling and upselling opportunities to the initial contact overlooks potential revenue opportunities.", others: "b327" },
        { english: "Generic campaigns may fail to resonate with leads as they lack personalization and relevance.", others: "b328" },
        { english: "Correct! Targeted campaigns aligned with lead preferences resonate best as they cater to individual needs.", others: "b329" },
        { english: "Campaigns with attractive content are likely to capture interest but may not be enough to increase engagement.", others: "b330" },
        { english: "It will overlook valuable insights for enhancing the customer experience.", others: "b331" },
        { english: "Correct! Continuously improving service based on customer feedback demonstrates a commitment to customer needs.", others: "b332" },
        { english: "Providing consistent service can lead to satisfaction but not improving it timely may negatively impact the experience.", others: "b333" },
        { english: "Failing to allocate surplus hours may result in insufficient resources to effectively manage the customer experience.", others: "b334" },
        { english: "Limiting surplus hours may restrict resources and hinder exceptional customer service delivery.", others: "b335" },
        { english: "Correct! Allocating surplus hours ensures adequate resources for optimal service delivery.", others: "b336" },
        { english: "Increasing resource spending may lead to unnecessary expenses and hinder cost optimization efforts.", others: "b337" },
        { english: "Correct! Optimizing resource allocation for cost efficiency ensures effective use of resources.", others: "b338" },
        { english: "Decreasing resource spending without considering the impact on service quality may compromise satisfaction.", others: "b339" },
        { english: "Maintaining the status quo may lead to stagnation and missed opportunities for improvement.", others: "b340" },
        { english: "Implementing processes only reducing pipeline velocity can lead to duplication of effort and unnecessary complexity.", others: "b341" },
        { english: "Correct! Identifying and eliminating inefficiencies is key to streamlining processes and improving operational efficiency.", others: "b342" },
      ],
    },
    {
      heading: "Readings",
      body: [
        { english: "Game Instructions", others: "b343" },
        { english: "Materials from Instructor", others: "b344" },
        { english: "Decision-making instruction", others: "b345" },
        { english: "The decision-making process is introduced in this document step-by-step", others: "b346" },
        { english: "Walkthrough video", others: "b347" },
        { english: "A tutorial on making step-by-step decisions", others: "b348" },
        { english: "Read", others: "b349" },
        { english: "View", others: "b350" },
      ],
    },
    {
      heading: "Forum",
      body: [
        { english: "Individual", others: "b351" },
        { english: "Course", others: "b352" },
        { english: "Welcome,", others: "b353" },
        { english: "Ready? Set. Chat! Let's jump right into things.", others: "b354" },
        { english: "New Topic", others: "b355" },
        { english: "To create a chat for this round, create a new topic first…", others: "b356" }
      ],
    },
    {
      heading: "Leaderboard",
      body: [
        { english: "Average Score", others: "b357" },
        { english: "Median Score", others: "b358" },
        { english: "Score Distribution", others: "b359" },
        { english: "The average score, median score and distribution curve are calculated on 1st KPI indicated on the left side of the below table", others: "b360" },
        { english: "Ranks", others: "b361" },
        { english: "Name", others: "b362" },
        { english: "Value Creation, INR", others: "b363" },
        { english: "Total Cost, INR", others: "b364" },
        { english: "Expected New Value, INR", others: "b365" },
        { english: "Quiz Mark", others: "b366" },
      ],
    },
    {
      heading: "Headings",
      body: [
        { english: "Decision area", others: "b367" },
        { english: "Instructor name", others: "b368" },
        { english: "Current round", others: "b369" },
        { english: "Game Timer", others: "b370" },
      ]
    },
    {
      heading: "Round",
      body: [
        { english: "Round", others: "b371" },

      ]
    },
    {
      heading:"General",
      body: [
        { english: "Submit", others: "b408" },
        { english: "Game Arena", others: "b3" },
        { english: "Readings", others: "b4" },
        { english: "Forum", others: "b5" },
        { english: "Leaderboard", others: "b6" },
        { english: "Introduction", others: "b395" },
        { english: "Implemented", others: "b396" },
        { english: "Not implemented", others: "b397" },
        { english: "show more", others: "b398" },
        { english: "show less", others: "b399" },
        { english: "Loading... Brewing up some digital magic!", others: "b407" },
      ]
    },
  ]
  selectedLanguage = 'english';
}
