import { Injectable } from '@angular/core';
import { CommonsheetdesignService } from '../sheetdesign/commonsheetdesign.service';
import { ApiService } from '../../backendgameapi/api.service';

@Injectable({
    providedIn: 'root'
})
export class EcommercesheetService extends CommonsheetdesignService {
    constructor(
        private _api: ApiService) {
        super();
    }
    excelalldata: any = [];
    ecommerceexcelformat: any = [];
    ecommercecolname = ["Catalog", "Product 1", "Product 2", "Product 3", "Product 4", "Product 5", "Product 6", "Product 7", "Product 8", "Product 9",
        "Product 10", "Markups %, Product 1", "Markups %, Product 2", "Markups %, Product 3", "Markups %, Product 4", "Markups %, Product 5",
        "Markups %, Product 6", "Markups %, Product 7", "Markups %, Product 8", "Markups %, Product 9", "Markups %, Product 10",
        "Estimated Market Share %, Product 1", "Estimated Market Share %, Product 2", "Estimated Market Share %, Product 3", "Estimated Market Share %, Product 4",
        "Estimated Market Share %, Product 5", "Estimated Market Share %, Product 6", "Estimated Market Share %, Product 7", "Estimated Market Share %, Product 8",
        "Estimated Market Share %, Product 9", "Estimated Market Share %, Product 10", "Buffer Coefficient, Product 1", "Buffer Coefficient, Product 2",
        "Buffer Coefficient, Product 3", "Buffer Coefficient, Product 4", "Buffer Coefficient, Product 5", "Buffer Coefficient, Product 6", "Buffer Coefficient, Product 7",
        "Buffer Coefficient, Product 8", "Buffer Coefficient, Product 9", "Buffer Coefficient, Product 10", "Marketing","Green Thread Initiative","Eco-Chic Fashion Week",
        "Seamseco Sustainable Challenge","Seamseco Style Stories","Seamseco Runway Reels","Eco-Influencer Challenge","Green Fabric Diaries","Seamseco Style Challenges","Eco-Innovator Interviews",
        "Email Tool","Welcome Email Priority","Product Highlight Email Priority","Educational Content Email Priority","Exclusive Offers Email Priority","Feedback and Engagement Email Priority",
        "Welcome Email Leads Type","Product Highlight Email Leads Type","Educational Content Leads Type","Exclusive Offers Leads Type","Feedback and Engagement Leads Type",
        "Sustainability-Centric Content Marketing","Influencer Collaborations","Pop-Up Shops and Experiential Events","Loyalty Program","Targeted Advertising Campaigns","Experience",
        "Website Design","Scarcity Indicator","Progress Bar for Checkout","Dynamic Exit-Intent Pop-Up","Personalized Recommendations","Social Proof Notifications","Checkout Page",
        "One-Click Checkout","Guest Checkout","Social Media Checkout","Customer Service System","Operations","Packaging","Logistics","Vendor Management Software","Advanced Material Quality Testing",
        "Blockchain for Supply Chain Transparency","Dynamic Pricing and Inventory Management Tool","Customer Relationship Management (CRM) Integration",
        "Organic Cotton T-shirt","Recycled Polyester Dress","Linen Summer Dress","Modal Fabric Maxi Skirt",
        "Silk Wrap Top","Lyocell Jumpsuit","Wool Blend Overcoat","Bamboo Fiber Sweater",
        "Recycled Nylon Jacket","Linen Button-Up Shirt","Modal Underwear","Eco-Wool Suit",
        "Lyocell Tee","Organic Cotton Socks","Recycled Fabric Scarf","Hemp Baseball Cap","Modal Shawl",
        "Eco-Friendly Backpack","Vegan Leather Wallet","Organic Linen Tote Bag",
        "Bamboo Fiber Blouse","Hemp Denim Jeans",
        "Eco-Fleece Hoodie","Organic Cotton Polo Shirt","Hemp Cargo Shorts","Organic Cotton Chinos","Recycled Leather Belt",
        "Bamboo Sunglasses","Silk Bandana","Recycled Rubber Sandals",
        "Social Media","Campaigns","Organic","Email","Bounce Rate","Engagement Rate","Customer Satisfaction","Revenue","Cost","Gross Profit/Loss","Promotion cost","Website cost","Personnel & Service cost",
        "Packaging cost","Logistics and Inventory cost","Process Improvement cost","Operating expense","EBITDA","Average Order Value, INR","Sales Performance Indication","Product Return","ROAS","Operating Margin",
        "Catalog","Marketing","Experience","Operations","Product Return, %","Operating Margin, %",
    ];

    downloadReportforgame(apiname: string, gamename: string, email: string, coursecode: string, studentsectionid: string, noofattempt: string, coursename: string,
        coursedetailsid: number) {
        let body =
        {
            email: email,
            caller: "student",
            usermode: "student",
            searchtype: "report",
            searchcontent: "",
            coursecode: coursecode,
            studentsectionid: studentsectionid,
            attempt: noofattempt,
            coursename: coursename,
            coursedetailsid: coursedetailsid

        }

        this._api.fetchexceldata(apiname, body).subscribe(
            (data: any) => {
                if (data.status == 'Success') {
                    if (gamename == "ecommercegame") {
                        this.createExcelReportforEcommerceGame(data);

                    }
                }
            })

    }

    createExcelReportforEcommerceGame(data: any) {
        this.excelalldata = [];
        for (let i = 0; i < data.resultList.length; i++) {
            this.ecommerceexcelformat = [
                [],
                ["", "Round" + Number(i + 1), "", "", "", "", "", "", "", "", "", "", ""],
                [],
                ["", "Decisions"],
                [],
                ["", "Parameter", "Input"],
                ["", "Catalog", ""],
                ["", "Product 1", data.resultList[i].ecommercegamedata.j8],
                ["", "Product 2", data.resultList[i].ecommercegamedata.j9],
                ["", "Product 3", data.resultList[i].ecommercegamedata.j10],
                ["", "Product 4", data.resultList[i].ecommercegamedata.j11],
                ["", "Product 5", data.resultList[i].ecommercegamedata.j12],
                ["", "Product 6", data.resultList[i].ecommercegamedata.j13],
                ["", "Product 7", data.resultList[i].ecommercegamedata.j14],
                ["", "Product 8", data.resultList[i].ecommercegamedata.j15],
                ["", "Product 9", data.resultList[i].ecommercegamedata.j16],
                ["", "Product 10", data.resultList[i].ecommercegamedata.j17],
                ["", "Markups %, Product 1",data.resultList[i].ecommercegamedata.ar46 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar46)*100).toFixed(0))],
                ["", "Markups %, Product 2",data.resultList[i].ecommercegamedata.ar47 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar47)*100).toFixed(0))],
                ["", "Markups %, Product 3", data.resultList[i].ecommercegamedata.ar48== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar48)*100).toFixed(0))],
                ["", "Markups %, Product 4",data.resultList[i].ecommercegamedata.ar49 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar49)*100).toFixed(0))],
                ["", "Markups %, Product 5",data.resultList[i].ecommercegamedata.ar50 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar50)*100).toFixed(0))],
                ["", "Markups %, Product 6",data.resultList[i].ecommercegamedata.ar51 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar51)*100).toFixed(0))],
                ["", "Markups %, Product 7",data.resultList[i].ecommercegamedata.ar52 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar52)*100).toFixed(0))],
                ["", "Markups %, Product 8",data.resultList[i].ecommercegamedata.ar53 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar53)*100).toFixed(0))],
                ["", "Markups %, Product 9", data.resultList[i].ecommercegamedata.ar54== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar54)*100).toFixed(0))],
                ["", "Markups %, Product 10",data.resultList[i].ecommercegamedata.ar55== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar55)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 1", data.resultList[i].ecommercegamedata.as46 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as46)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 2", data.resultList[i].ecommercegamedata.as47 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as47)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 3", data.resultList[i].ecommercegamedata.as48 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as48)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 4", data.resultList[i].ecommercegamedata.as49 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as49)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 5", data.resultList[i].ecommercegamedata.as50 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as50)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 6",data.resultList[i].ecommercegamedata.as51 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as51)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 7", data.resultList[i].ecommercegamedata.as52 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as52)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 8", data.resultList[i].ecommercegamedata.as53 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as53)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 9", data.resultList[i].ecommercegamedata.as54 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as54)*100).toFixed(0))],
                ["", "Estimated Market Share %, Product 10",data.resultList[i].ecommercegamedata.as55 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.as55)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 1",data.resultList[i].ecommercegamedata.ar58 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar58)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 2",data.resultList[i].ecommercegamedata.ar59 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar59)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 3", data.resultList[i].ecommercegamedata.ar60== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar60)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 4", data.resultList[i].ecommercegamedata.ar61== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar61)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 5",data.resultList[i].ecommercegamedata.ar62 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar62)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 6",data.resultList[i].ecommercegamedata.ar63 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar63)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 7",data.resultList[i].ecommercegamedata.ar64 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar64)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 8",data.resultList[i].ecommercegamedata.ar65 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar65)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 9",data.resultList[i].ecommercegamedata.ar66 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar66)*100).toFixed(0))],
                ["", "Buffer Coefficient, Product 10",data.resultList[i].ecommercegamedata.ar67== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.ar67)*100).toFixed(0))],
                ["", "Marketing", ""],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v10, data.resultList[i].ecommercegamedata.b49 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v11, data.resultList[i].ecommercegamedata.b50 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v12, data.resultList[i].ecommercegamedata.b51 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v16, data.resultList[i].ecommercegamedata.b55 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v17, data.resultList[i].ecommercegamedata.b56 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v18, data.resultList[i].ecommercegamedata.b57 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v22, data.resultList[i].ecommercegamedata.b61 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v23, data.resultList[i].ecommercegamedata.b62 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v24, data.resultList[i].ecommercegamedata.b63 == 1 ? "Implemented" : "Not Implemented"],
                ["", "Email Tool", data.resultList[i].ecommercegamedata.aq151],
                ["", "Welcome Email Priority",                 data.resultList[i].ecommercegamedata.f73 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.f73)*100).toFixed(0))],
                ["", "Product Highlight Email Priority",       data.resultList[i].ecommercegamedata.f74 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.f74)*100).toFixed(0))],
                ["", "Educational Content Email Priority",     data.resultList[i].ecommercegamedata.f75 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.f75)*100).toFixed(0))],
                ["", "Exclusive Offers Email Priority",        data.resultList[i].ecommercegamedata.f76 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.f76)*100).toFixed(0))],
                ["", "Feedback and Engagement Email Priority", data.resultList[i].ecommercegamedata.f77 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.f77)*100).toFixed(0))],
                ["", "Welcome Email Leads Type", data.resultList[i].ecommercegamedata.e73],
                ["", "Product Highlight Email Leads Type", data.resultList[i].ecommercegamedata.e74],
                ["", "Educational Content Leads Type", data.resultList[i].ecommercegamedata.e75],
                ["", "Exclusive Offers Leads Type", data.resultList[i].ecommercegamedata.e76],
                ["", "Feedback and Engagement Leads Type", data.resultList[i].ecommercegamedata.e77],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v86, data.resultList[i].ecommercegamedata.b83 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v87, data.resultList[i].ecommercegamedata.b84 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v88, data.resultList[i].ecommercegamedata.b85 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v89, data.resultList[i].ecommercegamedata.b86 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.v90, data.resultList[i].ecommercegamedata.b87 == 1 ? "Implemented" : "Not Implemented"],
                ["", "Experience", ""],
                ["", "Website Design", data.resultList[i].ecommercegamedata.aq152],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.ag15, data.resultList[i].ecommercegamedata.b103 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.ag16, data.resultList[i].ecommercegamedata.b104 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.ag17, data.resultList[i].ecommercegamedata.b105 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.ag18, data.resultList[i].ecommercegamedata.b106 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommerceGameCM.ecommercegameperioddata.ag19, data.resultList[i].ecommercegamedata.b107 == 1 ? "Implemented" : "Not Implemented"],
                ["", "Checkout Page", data.resultList[i].aq153],
                ["", data.resultList[i].ecommercegamedata.c116, data.resultList[i].ecommercegamedata.b116 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c117, data.resultList[i].ecommercegamedata.b117 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c118, data.resultList[i].ecommercegamedata.b118 == 1 ? "Implemented" : "Not Implemented"],
                ["", "Customer Service System", data.resultList[i].ecommercegamedata.aq154],
                ["", "Operations", ""],
                ["", "Packaging", data.resultList[i].ecommercegamedata.aq155],
                ["", "Logistics", data.resultList[i].ecommercegamedata.aq156],
                ["", data.resultList[i].ecommercegamedata.c134, data.resultList[i].ecommercegamedata.b134 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c135, data.resultList[i].ecommercegamedata.b135 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c136, data.resultList[i].ecommercegamedata.b136 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c137, data.resultList[i].ecommercegamedata.b137 == 1 ? "Implemented" : "Not Implemented"],
                ["", data.resultList[i].ecommercegamedata.c138, data.resultList[i].ecommercegamedata.b138 == 1 ? "Implemented" : "Not Implemented"],
                [],
                ["", "Sales, units", ""],
                [],
                ["", "Products", "Sales","Opportunity Loss","Inventory"],
                ["", data.resultList[i].ecommercegamedata.j8,     data.resultList[i].ecommercegamedata.n86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.n86).toFixed(0)),  data.resultList[i].ecommercegamedata.n87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.n87).toFixed(0)),data.resultList[i].ecommercegamedata.n88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.n88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j9,        data.resultList[i].ecommercegamedata.o86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o86).toFixed(0)), data.resultList[i].ecommercegamedata.o87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.o87).toFixed(0)), data.resultList[i].ecommercegamedata.o88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.o88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j10,       data.resultList[i].ecommercegamedata.p86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.p86).toFixed(0)), data.resultList[i].ecommercegamedata.p87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.p87).toFixed(0)), data.resultList[i].ecommercegamedata.p88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.p88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j11,  data.resultList[i].ecommercegamedata.q86== 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.q86).toFixed(0)), data.resultList[i].ecommercegamedata.q87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.q87).toFixed(0)), data.resultList[i].ecommercegamedata.q88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.q88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j12,       data.resultList[i].ecommercegamedata.r86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.r86).toFixed(0)), data.resultList[i].ecommercegamedata.r87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.r87).toFixed(0)), data.resultList[i].ecommercegamedata.r88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.r88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j13,   data.resultList[i].ecommercegamedata.s86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.s86).toFixed(0)), data.resultList[i].ecommercegamedata.s87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.s87).toFixed(0)), data.resultList[i].ecommercegamedata.s88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.s88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j14,   data.resultList[i].ecommercegamedata.t86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.t86).toFixed(0)), data.resultList[i].ecommercegamedata.t87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.t87).toFixed(0)), data.resultList[i].ecommercegamedata.t88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.t88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j15,       data.resultList[i].ecommercegamedata.u86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.u86).toFixed(0)), data.resultList[i].ecommercegamedata.u87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.u87).toFixed(0)), data.resultList[i].ecommercegamedata.u88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.u88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j16,            data.resultList[i].ecommercegamedata.v86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.v86).toFixed(0)), data.resultList[i].ecommercegamedata.v87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.v87).toFixed(0)), data.resultList[i].ecommercegamedata.v88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.v88).toFixed(0))],
                ["", data.resultList[i].ecommercegamedata.j17, data.resultList[i].ecommercegamedata.w86 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.w86).toFixed(0)), data.resultList[i].ecommercegamedata.w87 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.w87).toFixed(0)), data.resultList[i].ecommercegamedata.w88 == 0? "-" : Number(Number(data.resultList[i].ecommercegamedata.w88).toFixed(0))],
                [],
                ["","Product Margins",""],
                ["", "Products", "Pricing, INR","Margin %"],
                ["",data.resultList[i].ecommercegamedata.j8,  Number(Number(data.resultList[i].ecommercegamedata.m8).toFixed(0)),  Number((Number(data.resultList[i].ecommercegamedata.n95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j9,  Number(Number(data.resultList[i].ecommercegamedata.m9).toFixed(0)),  Number((Number(data.resultList[i].ecommercegamedata.o95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j10, Number(Number(data.resultList[i].ecommercegamedata.m10).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.p95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j11, Number(Number(data.resultList[i].ecommercegamedata.m11).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.q95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j12, Number(Number(data.resultList[i].ecommercegamedata.m12).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.r95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j13, Number(Number(data.resultList[i].ecommercegamedata.m13).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.s95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j14, Number(Number(data.resultList[i].ecommercegamedata.m14).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.t95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j15, Number(Number(data.resultList[i].ecommercegamedata.m15).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.u95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j16, Number(Number(data.resultList[i].ecommercegamedata.m16).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.v95)*100).toFixed(0)),],
                ["",data.resultList[i].ecommercegamedata.j17, Number(Number(data.resultList[i].ecommercegamedata.m17).toFixed(0)), Number((Number(data.resultList[i].ecommercegamedata.w95)*100).toFixed(0)),],
                [],
                ["","Promotion Distribution",""],
                [],
                ["","Parameters ","Visits ","Distribution, % "],
                ["","Social Media",data.resultList[i].ecommercegamedata.q57== 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.q57).toFixed(0)),data.resultList[i].ecommercegamedata.r57 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.r57)*100).toFixed(0))],
                ["","Campaigns",  data.resultList[i].ecommercegamedata.q58 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.q58).toFixed(0)),data.resultList[i].ecommercegamedata.r58 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.r58)*100).toFixed(0))],
                ["","Organic",    data.resultList[i].ecommercegamedata.q59 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.q59).toFixed(0)),data.resultList[i].ecommercegamedata.r59 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.r59)*100).toFixed(0))],
                ["","Email",      data.resultList[i].ecommercegamedata.q60 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.q60).toFixed(0)),data.resultList[i].ecommercegamedata.r60 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.r60)*100).toFixed(0))],
                [],
                ["","Website Experience"],
                [],
                ["","Parameters ","Output, % "],
                ["","Bounce Rate",data.resultList[i].ecommercegamedata.n78 == 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.n78)*100).toFixed(1))],
                ["","Engagement Rate",data.resultList[i].ecommercegamedata.n79 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.n79)*100).toFixed(1))],
                ["","Customer Satisfaction",data.resultList[i].ecommercegamedata.n80 == 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.n80)*100).toFixed(1))],
                [],
                ["","Income Statement, k INR"],
                [],
                ["","Parameters ","Output "],
                ["","Revenue",                    data.resultList[i].ecommercegamedata.o97 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o97).toFixed(0))],
                ["","Cost",                       data.resultList[i].ecommercegamedata.o98 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o98).toFixed(0))],
                ["","Gross Profit/Loss",          data.resultList[i].ecommercegamedata.o99 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o99).toFixed(0))],
                ["","Promotion cost",             data.resultList[i].ecommercegamedata.o101 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o101).toFixed(0))],
                ["","Website cost",               data.resultList[i].ecommercegamedata.o102 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o102).toFixed(0))],
                ["","Personnel & Service cost",   data.resultList[i].ecommercegamedata.o103 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o103).toFixed(0))],
                ["","Packaging cost",             data.resultList[i].ecommercegamedata.o104 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o104).toFixed(0))],
                ["","Logistics and Inventory cost",data.resultList[i].ecommercegamedata.o105 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o105).toFixed(0))],
                ["","Process Improvement cost",   data.resultList[i].ecommercegamedata.o106 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o106).toFixed(0))],
                ["","Operating expense",          data.resultList[i].ecommercegamedata.o107 == 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o107).toFixed(0))],
                ["","EBITDA",                      data.resultList[i].ecommercegamedata.o108== 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.o108).toFixed(0))],
                [],
                ["","KPI"],
                [],
                ["","Parameters ","Output "],
                ["","Average Order Value, INR", data.resultList[i].ecommercegamedata.r97== 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.r97).toFixed(0))],
                ["","Sales Performance Indication", data.resultList[i].ecommercegamedata.r98== 0 ? "-" : Number(Number(data.resultList[i].ecommercegamedata.r98.toFixed(1)))],
                ["","Product Return, %", data.resultList[i].ecommercegamedata.r100== 0 ? "-" : Number((Number(data.resultList[i].ecommercegamedata.r100)*100).toFixed(1))],
                ["","ROAS", data.resultList[i].ecommercegamedata.r99== 0 ? "-" :Number( Number(data.resultList[i].ecommercegamedata.r99.toFixed(0)))],
                ["","Operating Margin, %", data.resultList[i].ecommercegamedata.n109== 0 ? "-" :Number( (Number(data.resultList[i].ecommercegamedata.n109)*100).toFixed(1))],
                [],
                ["","Thinking Ability, %"],
                [],
                ["","Parameters ","Output "],
                ["","Catalog",   data.resultList[i].ecommercegamedata.aq162== 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.aq162)*100).toFixed(0))],
                ["","Marketing", data.resultList[i].ecommercegamedata.aq163== 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.aq163)*100).toFixed(0))],
                ["","Experience",data.resultList[i].ecommercegamedata.aq164== 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.aq164)*100).toFixed(0))],
                ["","Operations",data.resultList[i].ecommercegamedata.aq165== 0 ? "-" :Number((Number(data.resultList[i].ecommercegamedata.aq165)*100).toFixed(0))],
            ]
            this.excelalldata.push(this.ecommerceexcelformat)
        }
       
        this.excelSheetDesignFunction('ecommercegame', 'ecommercegame report', this.excelalldata, data.resultList.length, this.ecommercecolname);

    }
}